import type { MarketLesson } from "./market-lessons.js";

export const CRISIS_MARKET_LESSONS: MarketLesson[] = [
  {
    id: "sept-11-2001",
    title: "9.11同時多発テロ：安全保障ショックと航空・保険・防衛の再評価",
    period: "2001",
    direction: "volatile",
    category: "security_terror_shock",
    affectedTags: ["security", "defense", "airline", "travel", "insurance", "risk_off", "infrastructure"],
    shortSummary: "大規模テロで航空・旅行・保険が売られ、防衛・安全保障・警備関連が再評価された。市場はまずリスクオフになり、その後に政策対応とセクター再編を見る展開になった。",
    chain: ["大規模テロ", "市場停止/リスクオフ", "航空・旅行需要減", "保険損失", "安全保障・防衛支出増"],
    coreMechanism: "安全保障ショックは、需要消失と政策需要を同時に起こす。",
    earlySignals: ["航空需要急減", "保険損失見通し", "防衛予算", "警備規制強化", "旅行キャンセル"],
    wrongTakeaways: ["全産業が同じ影響を受ける", "事件後すぐ通常需要へ戻る", "防衛だけ見ればよい"],
    usefulTakeaways: ["一次被害と二次政策需要を分ける", "航空・旅行・保険・防衛・警備を分けて見る", "心理ショックと実需変化を区別する"],
    modernAnalogyQuestions: ["安全保障イベントは需要破壊か政策需要か？", "防衛・サイバー・通信インフラに波及するか？", "保険/旅行/航空への影響は一時的か構造的か？"],
    primaryChecks: ["政府発表", "航空需要", "保険損失", "防衛予算", "警備規制", "旅行統計"],
    sourceHints: ["September 11 attacks market impact", "airline insurance defense stocks"],
  },
  {
    id: "oil-embargo-1973",
    title: "第一次オイルショック：供給制限がインフレと省エネ投資を生む",
    period: "1973-1974",
    direction: "volatile",
    category: "energy_supply_shock",
    affectedTags: ["oil", "energy", "inflation", "consumer", "automotive", "materials", "macro"],
    shortSummary: "産油国の供給制限で原油価格が急騰し、インフレ、消費悪化、省エネ、代替エネルギー投資へ波及した。",
    chain: ["供給制限", "原油価格急騰", "インフレ", "消費/企業利益悪化", "省エネ・代替エネルギー投資"],
    coreMechanism: "エネルギーは全産業の入力コスト。供給ショックは物価と利益率を同時に揺らす。",
    earlySignals: ["産油国方針", "原油在庫", "価格統制/規制", "消費減速", "省エネ政策"],
    wrongTakeaways: ["資源価格は一部企業だけの問題", "インフレはすぐ収まる", "消費への影響は軽い"],
    usefulTakeaways: ["エネルギーコストの感応度を見る", "価格転嫁力を見る", "省エネ/代替技術の受益者を見る"],
    modernAnalogyQuestions: ["AI/データセンター時代の電力制約は新しいオイルショック的に効くか？", "エネルギー高を利益に変えられる企業か？"],
    primaryChecks: ["原油価格", "電力価格", "CPI", "価格転嫁", "省エネ投資", "政府政策"],
    sourceHints: ["1973 oil crisis", "oil embargo inflation"],
  },
  {
    id: "gulf-war-oil-1990",
    title: "湾岸危機/湾岸戦争：原油供給不安と資源価格ショック",
    period: "1990-1991",
    direction: "volatile",
    category: "geopolitical_oil_shock",
    affectedTags: ["oil", "energy", "defense", "inflation", "shipping", "geopolitics", "risk_off"],
    shortSummary: "中東情勢の悪化で原油供給不安が高まり、エネルギー、インフレ、防衛、海運、消費へ連鎖した。",
    chain: ["中東有事", "原油供給不安", "原油価格上昇", "インフレ/企業コスト増", "防衛・資源関連再評価"],
    coreMechanism: "地政学リスクは資源価格を通じて、企業利益と中央銀行政策へ波及する。",
    earlySignals: ["軍事緊張", "原油先物上昇", "海運保険料上昇", "防衛関連ニュース", "消費マインド悪化"],
    wrongTakeaways: ["遠い国の戦争は関係ない", "原油高は資源株だけ見ればいい", "短期で必ず元に戻る"],
    usefulTakeaways: ["資源価格→インフレ→金利→株式の連鎖を見る", "輸送/保険/防衛まで見る", "原油高の勝ち組と負け組を分ける"],
    modernAnalogyQuestions: ["今の地政学リスクは資源価格に効くか？", "原材料高を価格転嫁できる企業か？", "防衛・エネルギー政策が変わるか？"],
    primaryChecks: ["原油価格", "海運運賃", "防衛予算", "消費者物価", "企業の原材料感応度"],
    sourceHints: ["Gulf War oil price shock", "1990 oil shock markets"],
  },
  {
    id: "sars-2003",
    title: "SARS：感染症ショックは旅行・小売を直撃し、医療/防疫を再評価する",
    period: "2003",
    direction: "volatile",
    category: "infectious_disease_shock",
    affectedTags: ["healthcare", "travel", "airline", "retail", "testing", "vaccine", "risk_off"],
    shortSummary: "SARSはアジア中心に旅行・小売・航空へ大きな影響を与え、防疫、医療、検査、政府対応の重要性を市場に意識させた。",
    chain: ["感染拡大", "渡航/外出控え", "航空・ホテル・小売悪化", "医療/防疫需要", "収束後の需要回復"],
    coreMechanism: "感染症は行動制限と心理不安を通じて、需要を短期的に消す。",
    earlySignals: ["感染者増加", "渡航警戒", "WHO発表", "ホテル稼働率", "航空予約"],
    wrongTakeaways: ["感染症は医療株だけ見ればよい", "一度悪化した需要は戻らない", "地域限定なら世界市場に関係ない"],
    usefulTakeaways: ["旅行/消費の一次被害と医療/防疫の二次需要を分ける", "収束後のリバウンドも見る", "WHO/政府対応を重視する"],
    modernAnalogyQuestions: ["感染症ニュースは渡航/物流/医療のどこに効くか？", "防疫需要は一時的か継続的か？"],
    primaryChecks: ["WHO発表", "感染者数", "渡航制限", "航空予約", "ホテル稼働率", "検査/医療需要"],
    sourceHints: ["SARS 2003 market impact", "SARS travel stocks"],
  },
  {
    id: "mers-korea-2015",
    title: "MERS韓国流行：局地感染でも観光・消費に急ブレーキがかかる",
    period: "2015",
    direction: "volatile",
    category: "regional_health_shock",
    affectedTags: ["healthcare", "travel", "retail", "consumer", "tourism", "testing"],
    shortSummary: "MERSの韓国内流行は、感染規模以上に観光・小売・消費心理へ影響した。局地感染でも行動変化が大きいと企業業績に効く。",
    chain: ["局地感染", "病院/政府対応への不安", "外出/旅行控え", "小売・観光悪化", "収束後に回復"],
    coreMechanism: "感染症の市場影響は感染者数だけでなく、人々の行動変化で決まる。",
    earlySignals: ["病院内感染", "政府対応批判", "観光予約キャンセル", "小売客数減少"],
    wrongTakeaways: ["感染者数が少なければ経済影響も小さい", "局地感染なら無視できる"],
    usefulTakeaways: ["人流データを見る", "観光・小売・交通への心理影響を見る"],
    modernAnalogyQuestions: ["ニュースの恐怖が実際の行動変化に出ているか？", "観光/小売の需要減は一時的か？"],
    primaryChecks: ["感染者数", "人流", "観光予約", "小売売上", "政府対応"],
    sourceHints: ["MERS Korea 2015 economic impact", "tourism retail MERS"],
  },
  {
    id: "ebola-2014",
    title: "エボラ流行：公衆衛生・支援資金・物流制約の連鎖",
    period: "2014-2016",
    direction: "volatile",
    category: "global_health_emergency",
    affectedTags: ["healthcare", "vaccine", "testing", "logistics", "aid", "risk_off", "travel"],
    shortSummary: "エボラ流行では医療体制、国際支援、物流、渡航、ワクチン/検査開発が市場テーマになった。",
    chain: ["感染拡大", "医療体制逼迫", "WHO/国際支援", "渡航/物流影響", "ワクチン・検査・防疫需要"],
    coreMechanism: "公衆衛生ショックは、医療だけでなく物流・援助資金・国際移動へ波及する。",
    earlySignals: ["WHO緊急対応", "国境越え感染", "医療物資不足", "支援資金不足"],
    wrongTakeaways: ["遠い地域の感染症は市場に関係ない", "医薬品銘柄だけ見ればよい"],
    usefulTakeaways: ["医療・物流・支援資金をセットで見る", "渡航制限と市場心理を確認する"],
    modernAnalogyQuestions: ["WHO緊急事態はどの産業へ二次影響があるか？", "医療物資や物流にボトルネックはあるか？"],
    primaryChecks: ["WHO statement", "感染地域", "支援資金", "医療物資", "物流/渡航制限"],
    sourceHints: ["Ebola outbreak 2014 WHO emergency", "public health emergency market impact"],
  },
  {
    id: "mpox-2022-2024",
    title: "Mpox：WHO緊急事態とワクチン/検査/公衆衛生体制",
    period: "2022-2024",
    direction: "volatile",
    category: "public_health_emergency",
    affectedTags: ["healthcare", "vaccine", "testing", "who", "public_health", "logistics"],
    shortSummary: "MpoxはWHOの緊急事態宣言やワクチン供給、公衆衛生体制、地域医療の重要性を示した。",
    chain: ["感染拡大", "WHO緊急事態", "ワクチン/検査需要", "公衆衛生予算", "供給制約確認"],
    coreMechanism: "感染症テーマは、流行規模・政府対応・供給能力・市場心理の組み合わせで動く。",
    earlySignals: ["WHO発表", "感染地域拡大", "ワクチン在庫", "検査需要", "政府予算"],
    wrongTakeaways: ["宣言が出たら必ず医療株が上がる", "一時的ニュースだけで長期需要になる"],
    usefulTakeaways: ["宣言より実需と供給能力を見る", "ワクチン/検査が売上に変わるか確認する"],
    modernAnalogyQuestions: ["緊急事態宣言が企業売上に変わる経路はあるか？", "供給不足が価格決定力になるか？"],
    primaryChecks: ["WHO発表", "ワクチン供給", "検査件数", "政府調達", "企業開示"],
    sourceHints: ["Mpox public health emergency", "WHO mpox vaccine supply"],
  },
  {
    id: "great-east-japan-earthquake-2011",
    title: "東日本大震災：災害・原発・供給網・復興需要が同時発生",
    period: "2011",
    direction: "volatile",
    category: "earthquake_nuclear_supply_chain",
    affectedTags: ["japan", "earthquake", "nuclear", "energy", "construction", "insurance", "supply_chain", "semiconductor", "automotive"],
    shortSummary: "巨大地震と津波、原発事故、電力制約、サプライチェーン寸断、復興需要が同時に発生し、日本株と世界の製造業に広く影響した。",
    chain: ["巨大地震/津波", "原発事故/電力制約", "工場停止", "自動車/半導体供給網寸断", "復興需要/政策変更"],
    coreMechanism: "大災害は、被害企業だけでなく、電力・物流・部品供給・政策まで一気に変える。",
    earlySignals: ["工場停止", "電力制限", "物流停止", "保険損失", "復興予算"],
    wrongTakeaways: ["被災地企業だけ見ればよい", "復興需要だけで全部プラス", "原発問題は電力会社だけ"],
    usefulTakeaways: ["供給網のどこが止まるかを見る", "復興需要とコスト増を分ける", "エネルギー政策の変化を見る"],
    modernAnalogyQuestions: ["震災は供給停止か復興需要か？", "電力/物流/部品のボトルネックはどこか？"],
    primaryChecks: ["工場稼働", "電力供給", "物流", "復興予算", "保険損失", "部品在庫"],
    sourceHints: ["2011 Tohoku earthquake market impact", "Fukushima supply chain"],
  },
  {
    id: "fukushima-nuclear-policy-2011",
    title: "福島第一原発事故：原子力政策の再評価と電力構成の変化",
    period: "2011-",
    direction: "volatile",
    category: "nuclear_policy_shift",
    affectedTags: ["nuclear", "energy", "power", "renewable", "lng", "utility", "policy", "grid"],
    shortSummary: "原発事故で原子力政策が大きく変わり、LNG輸入、再エネ、電力料金、電力会社財務、エネルギー安全保障へ長期波及した。",
    chain: ["原発事故", "原発停止/安全規制強化", "火力/LNG依存増", "電力コスト上昇", "再エネ/原発再稼働議論"],
    coreMechanism: "エネルギー政策の変化は、電力価格、産業競争力、設備投資に長く効く。",
    earlySignals: ["原発停止", "規制強化", "LNG輸入増", "電力料金", "再エネ制度"],
    wrongTakeaways: ["事故後は原発関連が永久に終わる", "再エネだけで短期代替できる"],
    usefulTakeaways: ["電源構成を長期で見る", "政策・コスト・安定供給をセットで見る"],
    modernAnalogyQuestions: ["AI時代の電力需要で原子力/送電網の見方は変わるか？", "電力コストを価格転嫁できるか？"],
    primaryChecks: ["電源構成", "電力料金", "LNG価格", "原発再稼働", "再エネ制度", "送電網投資"],
    sourceHints: ["Fukushima nuclear policy", "Japan energy mix after Fukushima"],
  },
  {
    id: "thailand-floods-2011",
    title: "タイ洪水：遠い災害が世界の自動車・HDD供給網を止める",
    period: "2011",
    direction: "volatile",
    category: "flood_supply_chain",
    affectedTags: ["flood", "supply_chain", "automotive", "electronics", "hdd", "manufacturing", "insurance"],
    shortSummary: "タイ洪水で工業団地が被災し、自動車部品やHDDなど世界供給網に影響した。遠い地域の災害でも部品供給が止まると世界企業に波及する。",
    chain: ["洪水", "工業団地浸水", "部品工場停止", "自動車/HDD供給不足", "価格上昇/生産調整"],
    coreMechanism: "集中した製造拠点が災害で止まると、世界の完成品メーカーへ波及する。",
    earlySignals: ["工業団地浸水", "工場停止", "部品納期遅延", "在庫減少", "保険損失"],
    wrongTakeaways: ["海外の洪水は国内企業に関係ない", "完成品メーカーだけ見ればよい"],
    usefulTakeaways: ["部品供給の地域集中を見る", "在庫と代替調達を見る", "サプライヤーまで追う"],
    modernAnalogyQuestions: ["サプライチェーンは特定地域に集中していないか？", "代替調達は可能か？"],
    primaryChecks: ["工場所在地", "供給元集中", "在庫", "代替調達", "納期", "保険"],
    sourceHints: ["2011 Thailand floods supply chain", "HDD shortage Thailand flood"],
  },
  {
    id: "kumamoto-earthquake-2016",
    title: "熊本地震：半導体・自動車部品の局地停止が全国生産に波及",
    period: "2016",
    direction: "volatile",
    category: "regional_earthquake_supply_chain",
    affectedTags: ["japan", "earthquake", "semiconductor", "automotive", "electronics", "supply_chain", "manufacturing"],
    shortSummary: "熊本地震では半導体・部品工場の停止が、自動車や電子機器の生産へ波及した。局地災害でも重要部品が止まると影響は大きい。",
    chain: ["地震", "部品/半導体工場停止", "完成品生産調整", "代替調達", "復旧後の在庫積み増し"],
    coreMechanism: "重要部品は小さな地域停止でも大きな完成品生産へ波及する。",
    earlySignals: ["工場稼働停止", "主要顧客の生産調整", "在庫水準", "復旧見通し"],
    wrongTakeaways: ["局地災害だから限定的", "完成品メーカーの所在地だけ見ればよい"],
    usefulTakeaways: ["キーパーツの所在地を見る", "顧客の生産計画を見る", "復旧時期を確認する"],
    modernAnalogyQuestions: ["半導体/部品の集中リスクはどこにあるか？", "復旧遅延が売上に効くか？"],
    primaryChecks: ["工場所在地", "稼働状況", "顧客生産", "在庫", "復旧計画"],
    sourceHints: ["2016 Kumamoto earthquake semiconductor auto supply chain"],
  },
  {
    id: "noto-earthquake-2024",
    title: "能登半島地震：地域災害・復旧遅延・観光/インフラ/建設需要",
    period: "2024",
    direction: "volatile",
    category: "regional_disaster_reconstruction",
    affectedTags: ["japan", "earthquake", "construction", "tourism", "infrastructure", "insurance", "logistics"],
    shortSummary: "能登半島地震では交通・水道・観光・地域産業の復旧遅延が課題になり、復興需要と地域経済の落ち込みを分けて見る必要がある。",
    chain: ["地震", "インフラ損傷", "物流/観光悪化", "復旧工事", "地域経済回復まで時間差"],
    coreMechanism: "地域災害は復興需要を生む一方、観光・小売・物流にはマイナスが先に出る。",
    earlySignals: ["道路/水道復旧", "宿泊キャンセル", "復興予算", "建設人手不足", "保険支払い"],
    wrongTakeaways: ["災害＝建設株に全部プラス", "地域経済へのマイナスはすぐ戻る"],
    usefulTakeaways: ["復興需要と需要消失を分ける", "人手不足で復旧が遅れる可能性を見る"],
    modernAnalogyQuestions: ["災害後の人手不足は復興需要を制約していないか？", "観光/物流への影響は続くか？"],
    primaryChecks: ["復興予算", "道路/水道復旧", "宿泊データ", "建設人員", "保険支払い"],
    sourceHints: ["2024 Noto Peninsula earthquake economic impact", "Japan reconstruction demand"],
  },
  {
    id: "chernobyl-1986",
    title: "チェルノブイリ事故：原子力リスクと長期政策不信",
    period: "1986",
    direction: "volatile",
    category: "nuclear_accident_policy",
    affectedTags: ["nuclear", "energy", "policy", "healthcare", "agriculture", "risk_off", "utility"],
    shortSummary: "チェルノブイリ事故は原子力政策、公衆衛生、食品安全、地域経済へ長期影響を与えた。原発事故は単なる設備事故ではなく政策信頼を壊す。",
    chain: ["原発事故", "放射性物質拡散", "健康/食品不安", "原子力政策見直し", "代替電源議論"],
    coreMechanism: "原子力事故は、設備損害よりも信頼・規制・政策の長期変化が大きい。",
    earlySignals: ["事故情報の不透明性", "避難", "食品規制", "原発停止", "規制強化"],
    wrongTakeaways: ["事故処理だけ見ればよい", "政策影響は短期で終わる"],
    usefulTakeaways: ["情報透明性を見る", "規制強化と代替電源をセットで見る"],
    modernAnalogyQuestions: ["原子力政策は安全保障/電力需要で再評価されるか？", "事故時の情報開示は信頼できるか？"],
    primaryChecks: ["規制発表", "原発稼働", "電力価格", "食品規制", "代替電源投資"],
    sourceHints: ["Chernobyl disaster nuclear policy", "nuclear market impact"],
  },
  {
    id: "hurricane-katrina-2005",
    title: "ハリケーン・カトリーナ：災害がエネルギー・保険・建設へ波及",
    period: "2005",
    direction: "volatile",
    category: "hurricane_energy_insurance",
    affectedTags: ["hurricane", "energy", "oil", "insurance", "construction", "infrastructure", "logistics"],
    shortSummary: "大規模ハリケーンで石油精製・港湾・保険・住宅復旧に影響し、自然災害がエネルギー供給と保険損失を通じて市場へ波及した。",
    chain: ["大型ハリケーン", "精製/港湾停止", "エネルギー供給不安", "保険損失", "復旧/建設需要"],
    coreMechanism: "自然災害は物理インフラを通じて、資源供給・物流・保険・建設へ波及する。",
    earlySignals: ["進路予測", "精製施設停止", "港湾停止", "保険損失見積り", "復旧予算"],
    wrongTakeaways: ["災害は建設にプラスだけ", "保険会社は保険料を上げればよいだけ"],
    usefulTakeaways: ["保険損失と再保険を見る", "重要インフラ停止を確認する"],
    modernAnalogyQuestions: ["気候災害で保険料/再保険が構造変化していないか？", "エネルギー/物流インフラに集中リスクはあるか？"],
    primaryChecks: ["保険損失", "再保険料", "港湾/精製稼働", "復旧予算", "住宅需要"],
    sourceHints: ["Hurricane Katrina economic impact", "energy insurance market impact"],
  },
  {
    id: "ever-given-suez-2021",
    title: "スエズ運河座礁：一本の物流動脈が世界供給網を止める",
    period: "2021",
    direction: "volatile",
    category: "shipping_chokepoint",
    affectedTags: ["shipping", "logistics", "supply_chain", "trade", "energy", "consumer", "inflation"],
    shortSummary: "Ever Givenの座礁でスエズ運河が一時封鎖され、海運・物流・在庫・エネルギー輸送の重要性が再認識された。",
    chain: ["運河封鎖", "船舶滞留", "納期遅延", "在庫不足", "物流コスト/代替ルート"],
    coreMechanism: "世界貿易にはチョークポイントがあり、一箇所の詰まりが広範な納期とコストに波及する。",
    earlySignals: ["主要航路停止", "滞留船舶数", "運賃上昇", "在庫不足", "代替航路"],
    wrongTakeaways: ["数日なら影響なし", "海運会社だけの問題"],
    usefulTakeaways: ["物流チョークポイントを見る", "在庫と代替ルートを見る"],
    modernAnalogyQuestions: ["紅海/台湾海峡/ホルムズなどの物流リスクは？", "在庫バッファは十分か？"],
    primaryChecks: ["運賃", "船舶滞留", "納期", "在庫", "代替ルート", "港湾混雑"],
    sourceHints: ["Ever Given Suez Canal blockage", "shipping supply chain impact"],
  },
  {
    id: "red-sea-shipping-2023",
    title: "紅海リスク：地政学が海運ルートとインフレに波及",
    period: "2023-2024",
    direction: "volatile",
    category: "shipping_geopolitical_risk",
    affectedTags: ["shipping", "logistics", "geopolitics", "trade", "energy", "inflation", "supply_chain"],
    shortSummary: "紅海周辺の攻撃リスクで船舶が迂回し、運賃、納期、エネルギー輸送、インフレ圧力へ波及した。",
    chain: ["地政学緊張", "航路リスク", "喜望峰迂回", "運賃/納期上昇", "企業コスト増"],
    coreMechanism: "物流ルートの安全性は、コスト・在庫・納期・物価に直結する。",
    earlySignals: ["船舶攻撃", "保険料上昇", "運賃上昇", "迂回増加", "港湾混雑"],
    wrongTakeaways: ["局地紛争なら物流には関係ない", "運賃上昇は海運株だけの話"],
    usefulTakeaways: ["物流コストを企業利益に接続する", "保険料と迂回日数を見る"],
    modernAnalogyQuestions: ["供給網のルートは安全か？", "運賃上昇を価格転嫁できるか？"],
    primaryChecks: ["海運運賃", "保険料", "迂回日数", "港湾混雑", "企業の物流費"],
    sourceHints: ["Red Sea shipping crisis", "Houthi attacks shipping costs"],
  },
  {
    id: "taiwan-earthquake-2024",
    title: "台湾地震：半導体供給網の集中リスクを再確認",
    period: "2024",
    direction: "volatile",
    category: "semiconductor_geographic_concentration",
    affectedTags: ["taiwan", "earthquake", "semiconductor", "tsmc", "supply_chain", "electronics", "ai"],
    shortSummary: "台湾地震は半導体製造の地理的集中リスクを再認識させた。AI・スマホ・自動車など広い産業が先端半導体に依存している。",
    chain: ["地震", "半導体工場点検/停止", "供給不安", "顧客生産計画確認", "地理分散/在庫再評価"],
    coreMechanism: "重要産業が一地域に集中していると、自然災害が世界の技術産業へ波及する。",
    earlySignals: ["工場停止", "歩留まり影響", "顧客コメント", "在庫水準", "代替生産"],
    wrongTakeaways: ["短期停止なら完全に無視できる", "半導体メーカーだけ見ればよい"],
    usefulTakeaways: ["地理集中リスクを見る", "顧客側の在庫と代替調達を見る"],
    modernAnalogyQuestions: ["AI/自動車/スマホの供給網は台湾依存か？", "国内回帰や分散投資が進むか？"],
    primaryChecks: ["工場稼働", "顧客在庫", "代替生産", "歩留まり", "出荷見通し"],
    sourceHints: ["2024 Taiwan earthquake semiconductor", "TSMC earthquake impact"],
  },
  {
    id: "israel-hamas-2023",
    title: "イスラエル・ハマス戦争：中東リスクと防衛・エネルギー・物流不安",
    period: "2023-",
    direction: "volatile",
    category: "regional_war_middle_east",
    affectedTags: ["war", "middle_east", "defense", "energy", "shipping", "risk_off", "geopolitics"],
    shortSummary: "中東情勢悪化は、防衛、原油、物流、航空、リスクオフ心理に波及する。直接の産油国でなくても地域拡大リスクが市場を動かす。",
    chain: ["軍事衝突", "地域拡大懸念", "原油/海運リスク", "防衛需要", "市場心理悪化"],
    coreMechanism: "中東リスクは実際の供給停止前でも、期待と保険料とリスクプレミアムを動かす。",
    earlySignals: ["地域拡大", "原油価格", "海運リスク", "航空運休", "防衛発注"],
    wrongTakeaways: ["直接関係国だけ見ればよい", "原油が上がらなければ影響なし"],
    usefulTakeaways: ["地域拡大確率と物流/保険料を見る", "防衛・エネルギー・航空を分ける"],
    modernAnalogyQuestions: ["中東リスクは物流/エネルギーに広がっているか？", "防衛関連は実受注につながるか？"],
    primaryChecks: ["原油価格", "海運保険料", "航空運航", "防衛予算", "政府発表"],
    sourceHints: ["Israel Hamas war market impact", "Middle East oil shipping risk"],
  },
  {
    id: "arab-spring-2011",
    title: "アラブの春：政治不安が資源・観光・通貨へ波及",
    period: "2011",
    direction: "volatile",
    category: "political_instability",
    affectedTags: ["politics", "emerging_market", "oil", "tourism", "currency", "risk_off"],
    shortSummary: "政治不安は観光、通貨、資源、海外企業の進出リスクを変える。民主化期待と混乱リスクが同時に存在する。",
    chain: ["政治デモ", "政権不安", "観光/投資減速", "通貨不安", "資源/地域リスク再評価"],
    coreMechanism: "政治体制の変化は、需要だけでなく通貨・契約・規制・治安を同時に変える。",
    earlySignals: ["大規模デモ", "政府対応", "観光客減", "通貨安", "資本流出"],
    wrongTakeaways: ["政治ニュースは株に関係ない", "民主化なら必ず市場にプラス"],
    usefulTakeaways: ["政治変化の短期混乱と長期改革を分ける", "観光/通貨/投資を確認する"],
    modernAnalogyQuestions: ["政権交代や大統領選が規制/補助金を変えるか？", "通貨と観光に影響するか？"],
    primaryChecks: ["政権動向", "通貨", "観光統計", "資本流出", "規制変更"],
    sourceHints: ["Arab Spring market impact", "political instability tourism currency"],
  },
  {
    id: "brexit-2016",
    title: "Brexit：政治イベントが通貨・金融・サプライチェーンを変える",
    period: "2016-2020",
    direction: "volatile",
    category: "referendum_policy_currency",
    affectedTags: ["election", "referendum", "currency", "finance", "trade", "supply_chain", "policy"],
    shortSummary: "Brexitは投票イベントで終わらず、ポンド安、金融拠点、貿易ルール、サプライチェーン、企業移転へ長期波及した。",
    chain: ["国民投票", "通貨急落", "金融/貿易ルール不透明", "企業移転/サプライチェーン変更", "長期交渉"],
    coreMechanism: "政治イベントは結果発表より、その後の制度設計が企業価値に効く。",
    earlySignals: ["世論調査", "通貨ボラ", "企業移転計画", "貿易交渉", "金融規制"],
    wrongTakeaways: ["投票日だけ見ればよい", "通貨安は全部プラス"],
    usefulTakeaways: ["制度変更の中身を見る", "通貨・貿易・人材移動をセットで見る"],
    modernAnalogyQuestions: ["大統領選/政権交代は制度をどう変えるか？", "企業は拠点や供給網を変えるか？"],
    primaryChecks: ["通貨", "貿易協定", "金融規制", "企業移転", "関税/労働移動"],
    sourceHints: ["Brexit market impact", "pound currency supply chain"],
  },
  {
    id: "covid-logistics-shortage-2021",
    title: "コロナ後の物流混乱：需要回復と供給制約でコストが跳ねる",
    period: "2020-2022",
    direction: "volatile",
    category: "post_pandemic_supply_chain",
    affectedTags: ["covid", "logistics", "shipping", "semiconductor", "inflation", "consumer", "supply_chain"],
    shortSummary: "コロナ後の需要回復と港湾混雑、コンテナ不足、半導体不足が重なり、物流費・納期・価格転嫁が企業業績を左右した。",
    chain: ["需要急回復", "港湾/コンテナ不足", "半導体不足", "物流費上昇", "価格転嫁/在庫戦略"],
    coreMechanism: "需要が戻っても供給網が詰まると、売上機会よりコスト増が先に出る企業がある。",
    earlySignals: ["運賃上昇", "港湾混雑", "納期長期化", "在庫不足", "価格改定"],
    wrongTakeaways: ["需要回復なら全企業にプラス", "物流費は一時的で無視できる"],
    usefulTakeaways: ["需要と供給制約を同時に見る", "価格転嫁力と在庫を見る"],
    modernAnalogyQuestions: ["AI/EV/宇宙でも供給制約が利益を削らないか？", "物流コストを転嫁できるか？"],
    primaryChecks: ["海運運賃", "納期", "在庫", "価格改定", "粗利率"],
    sourceHints: ["COVID supply chain disruption", "container shortage semiconductor shortage"],
  },
  {
    id: "avian-flu-food-2022",
    title: "鳥インフル：食品供給・卵価格・外食原価への連鎖",
    period: "2022-2024",
    direction: "volatile",
    category: "food_supply_health_shock",
    affectedTags: ["food", "agriculture", "health", "inflation", "restaurant", "consumer", "supply_chain"],
    shortSummary: "鳥インフルは養鶏・卵価格・食品メーカー・外食原価・消費者物価へ波及した。感染症は人間だけでなく食品供給にも効く。",
    chain: ["家禽感染", "殺処分/供給減", "卵/鶏肉価格上昇", "食品/外食原価増", "価格転嫁"],
    coreMechanism: "食品供給ショックは低単価商品ほど消費者心理と企業原価に効きやすい。",
    earlySignals: ["感染確認", "殺処分数", "卵価格", "外食値上げ", "在庫"],
    wrongTakeaways: ["人間の感染症でなければ市場に関係ない", "食品価格はすぐ戻る"],
    usefulTakeaways: ["食品原価と価格転嫁を見る", "供給回復までの時間差を見る"],
    modernAnalogyQuestions: ["食品供給ショックはどの企業の原価に効くか？", "価格転嫁は進むか？"],
    primaryChecks: ["感染数", "殺処分", "卵価格", "食品メーカー粗利", "外食価格"],
    sourceHints: ["avian flu egg prices", "food supply shock"],
  },
  {
    id: "turkey-earthquake-2023",
    title: "トルコ・シリア地震：通貨・建設・保険・復興資金の複合ショック",
    period: "2023",
    direction: "volatile",
    category: "emerging_market_disaster",
    affectedTags: ["earthquake", "emerging_market", "construction", "insurance", "currency", "aid", "infrastructure"],
    shortSummary: "大地震は人的被害だけでなく、通貨不安、財政負担、建設需要、保険、国際支援へ広く波及する。新興国では財政・通貨面も重要。",
    chain: ["大地震", "インフラ被害", "財政/通貨不安", "復興資金", "建設/保険/資材需要"],
    coreMechanism: "災害は国の財政余力と通貨信認によって、市場影響が大きく変わる。",
    earlySignals: ["被害額", "通貨下落", "国際支援", "復興予算", "建設資材価格"],
    wrongTakeaways: ["復興需要だけ見ればよい", "災害国の通貨/財政は関係ない"],
    usefulTakeaways: ["財政・通貨・復興需要を同時に見る", "建設需要とインフレ圧力を分ける"],
    modernAnalogyQuestions: ["災害国の財政余力はあるか？", "復興需要は企業利益に届くか？"],
    primaryChecks: ["被害額", "通貨", "復興予算", "国際支援", "建設資材価格"],
    sourceHints: ["Turkey Syria earthquake economic impact", "reconstruction currency risk"],
  },
  {
    id: "ukraine-war-2022",
    title: "ロシア・ウクライナ侵攻：地政学とエネルギー・食料・防衛の再評価",
    period: "2022-",
    direction: "volatile",
    category: "war_energy_food_security",
    affectedTags: ["war", "energy", "oil", "gas", "food", "defense", "inflation", "sanction", "shipping"],
    shortSummary: "侵攻と制裁でエネルギー、穀物、肥料、物流、防衛、インフレが同時に動いた。戦争は資源価格と政策支出を通じて広範囲に波及する。",
    chain: ["軍事侵攻", "制裁/供給不安", "エネルギー・穀物価格上昇", "インフレ/金利上昇", "防衛・資源・食料安全保障再評価"],
    coreMechanism: "戦争は直接被害だけでなく、資源・食料・物流・制裁・政策予算を通じて世界の利益配分を変える。",
    earlySignals: ["軍事緊張", "制裁", "資源価格", "穀物価格", "防衛予算", "難民/移民"],
    wrongTakeaways: ["遠い戦争は関係ない", "防衛株だけ見ればよい", "資源価格だけで判断できる"],
    usefulTakeaways: ["資源・食料・物流・防衛・移民を一体で見る", "制裁で勝ち組/負け組が変わる"],
    modernAnalogyQuestions: ["戦争はどの供給網を詰まらせるか？", "防衛/エネルギー/食料安全保障の国策に変わるか？"],
    primaryChecks: ["制裁", "原油/ガス/穀物", "防衛予算", "物流", "難民/移民政策"],
    sourceHints: ["Russia Ukraine war market impact", "energy food defense stocks"],
  },
];
