import type { MarketLesson } from "./market-lessons.js";

export const STRUCTURAL_RISK_MARKET_LESSONS: MarketLesson[] = [
  {
    id: "taiwan-drought-semiconductor-2021",
    title: "台湾干ばつと半導体：水不足が先端製造のボトルネックになる",
    period: "2021",
    direction: "volatile",
    category: "water_semiconductor_constraint",
    affectedTags: ["water", "drought", "semiconductor", "taiwan", "tsmc", "supply_chain", "ai", "datacenter"],
    shortSummary: "台湾の深刻な干ばつは、半導体製造が水資源に強く依存することを市場に再認識させた。AI/半導体時代は水・電力・土地がボトルネックになる。",
    chain: ["降雨不足", "工業用水制限", "半導体工場の稼働懸念", "顧客の供給不安", "地理分散・在庫・水リサイクル投資"],
    coreMechanism: "先端製造は電力だけでなく大量の超純水に依存するため、水不足が供給制約と価格決定力に直結する。",
    earlySignals: ["貯水率低下", "取水制限", "工業用水優先配分", "半導体企業コメント", "顧客在庫"],
    wrongTakeaways: ["水不足は農業だけの問題", "半導体は電力だけ見ればよい"],
    usefulTakeaways: ["水・電力・土地を製造ボトルネックとして見る", "地理集中リスクと代替生産を見る"],
    modernAnalogyQuestions: ["AIサプライチェーンは水不足に弱くないか？", "データセンターや半導体工場の水使用は規制されないか？"],
    primaryChecks: ["貯水率", "水使用規制", "工場所在地", "顧客在庫", "水リサイクル投資"],
    sourceHints: ["Taiwan drought 2021 semiconductor", "TSMC water shortage"],
  },
  {
    id: "california-drought-agriculture-power",
    title: "カリフォルニア干ばつ：農業・電力・食品価格の連鎖",
    period: "2012-2016 / 2020s",
    direction: "volatile",
    category: "drought_food_power",
    affectedTags: ["water", "drought", "agriculture", "food", "power", "inflation", "insurance", "climate"],
    shortSummary: "干ばつは農産物供給、水力発電、山火事リスク、食品価格、保険料へ波及する。気候リスクは単発ではなく慢性的なコスト構造になる。",
    chain: ["降水不足", "農業用水制限", "農産物価格上昇", "水力発電低下/電力不安", "保険・山火事・食品インフレ"],
    coreMechanism: "水不足は農業だけでなく電力・保険・消費者物価へ伝わる入力コストショック。",
    earlySignals: ["干ばつ指数", "貯水率", "農産物価格", "電力需給", "山火事リスク"],
    wrongTakeaways: ["干ばつは地域農家だけの話", "食品価格への影響は小さい"],
    usefulTakeaways: ["食料・電力・保険を一体で見る", "気候リスクの長期化を考える"],
    modernAnalogyQuestions: ["水不足が食品/電力/保険に同時波及していないか？", "価格転嫁できる企業か？"],
    primaryChecks: ["干ばつ指数", "貯水率", "農産物価格", "電力価格", "保険料"],
    sourceHints: ["California drought agriculture power prices", "drought food inflation"],
  },
  {
    id: "europe-migration-politics-2015",
    title: "欧州難民危機：移民・社会不安・政治分断が政策を変える",
    period: "2015-2016",
    direction: "volatile",
    category: "migration_political_fragmentation",
    affectedTags: ["migration", "politics", "europe", "security", "housing", "labor", "election", "social_unrest"],
    shortSummary: "難民流入は人道問題に加え、住宅、治安、労働市場、財政、選挙、ポピュリズムに波及した。移民は労働供給と政治リスクの両面で見る必要がある。",
    chain: ["紛争/貧困による移動", "受け入れ国の住宅/財政負担", "社会不安", "反移民政党台頭", "政策変更/規制強化"],
    coreMechanism: "移民は労働力不足を補う一方、住宅・財政・治安・文化摩擦が政治リスクを増幅する。",
    earlySignals: ["入国者数", "住宅逼迫", "治安報道", "世論調査", "選挙結果"],
    wrongTakeaways: ["移民は労働力として必ずプラス", "政治不安は市場に関係ない"],
    usefulTakeaways: ["労働供給メリットと政治/住宅コストを分ける", "選挙と政策転換を見る"],
    modernAnalogyQuestions: ["移民増加は人手不足解消か社会分断か？", "住宅・治安・選挙に波及していないか？"],
    primaryChecks: ["移民統計", "住宅価格/賃料", "世論調査", "選挙公約", "労働需給"],
    sourceHints: ["European migrant crisis 2015 political impact", "migration labor housing election"],
  },
  {
    id: "japan-foreign-workers-labor-shortage",
    title: "日本の外国人材・人手不足：労働力補完と社会インフラ需要",
    period: "2010s-2020s",
    direction: "volatile",
    category: "labor_shortage_migration_japan",
    affectedTags: ["japan", "migration", "labor_shortage", "staffing", "housing", "education", "healthcare", "automation", "robotics"],
    shortSummary: "日本の人手不足は外国人材、介護、物流、建設、外食、教育、住宅、行政サービス、自動化投資に波及する長期テーマ。",
    chain: ["高齢化/人口減", "人手不足", "外国人材受け入れ", "生活インフラ需要", "自動化/省人化投資"],
    coreMechanism: "労働力不足は賃金上昇と供給制約を生む一方、人材・教育・住宅・ロボット・SaaS需要を作る。",
    earlySignals: ["求人倍率", "在留外国人統計", "賃金上昇", "人件費率", "省人化投資"],
    wrongTakeaways: ["人手不足は全部の企業にプラス", "移民増加は単純に消費増だけ"],
    usefulTakeaways: ["人件費を価格転嫁できるか見る", "生活インフラと自動化需要を分ける"],
    modernAnalogyQuestions: ["外国人材増加で伸びる生活サービスは？", "人手不足を省人化で解決できる企業か？"],
    primaryChecks: ["求人倍率", "在留外国人統計", "人件費率", "価格転嫁", "省人化投資"],
    sourceHints: ["Japan labor shortage foreign workers", "aging demographics automation Japan"],
  },
  {
    id: "colonial-pipeline-cyberattack-2021",
    title: "Colonial Pipelineサイバー攻撃：デジタル攻撃が燃料供給を止める",
    period: "2021",
    direction: "volatile",
    category: "critical_infrastructure_cyberattack",
    affectedTags: ["cybersecurity", "energy", "pipeline", "fuel", "infrastructure", "ransomware", "logistics"],
    shortSummary: "ランサムウェア攻撃で米国東海岸の燃料供給網に混乱が発生し、サイバーが物理インフラの供給制約になることが示された。",
    chain: ["ランサムウェア", "パイプライン停止", "燃料不足/買い占め", "政府対応", "重要インフラのサイバー投資"],
    coreMechanism: "サイバー攻撃はIT障害ではなく、燃料・物流・医療・電力など現実の供給停止に直結する。",
    earlySignals: ["ランサムウェア増加", "重要インフラ障害", "政府警告", "燃料在庫", "サイバー保険料"],
    wrongTakeaways: ["サイバーはIT企業だけの話", "復旧すれば市場影響はゼロ"],
    usefulTakeaways: ["重要インフラの停止時間を見る", "サイバー投資と保険コストを見る"],
    modernAnalogyQuestions: ["攻撃対象は金融/病院/電力/物流に広がるか？", "サイバー対策需要は実受注に変わるか？"],
    primaryChecks: ["障害範囲", "復旧時間", "政府勧告", "サイバー保険", "セキュリティ投資"],
    sourceHints: ["Colonial Pipeline ransomware market impact", "critical infrastructure cyberattack"],
  },
  {
    id: "notpetya-2017",
    title: "NotPetya：サイバー攻撃が世界企業の物流・会計・生産を止める",
    period: "2017",
    direction: "volatile",
    category: "global_cyber_supply_chain",
    affectedTags: ["cybersecurity", "supply_chain", "shipping", "logistics", "ransomware", "manufacturing", "insurance"],
    shortSummary: "NotPetyaはウクライナ発の攻撃が海運・製薬・製造など世界企業へ広がり、サイバー地政学リスクを顕在化させた。",
    chain: ["国家/地政学的サイバー攻撃", "企業システム停止", "物流/生産混乱", "損害保険/サイバー保険", "防御投資"],
    coreMechanism: "サイバー攻撃は国境を越え、物流・会計・製造・保険に同時被害を出す可能性がある。",
    earlySignals: ["地政学緊張", "大規模マルウェア", "企業システム停止", "保険請求", "港湾/物流障害"],
    wrongTakeaways: ["攻撃対象国だけの問題", "バックアップがあればすぐ戻る"],
    usefulTakeaways: ["サプライチェーンのIT依存を確認する", "保険の戦争免責も見る"],
    modernAnalogyQuestions: ["地政学リスクがサイバーで企業に届くか？", "物流/病院/金融が止まるリスクは？"],
    primaryChecks: ["攻撃範囲", "復旧日数", "保険適用", "地政学緊張", "重要システム依存"],
    sourceHints: ["NotPetya cyberattack economic impact", "Maersk NotPetya"],
  },
  {
    id: "texas-power-crisis-2021",
    title: "テキサス電力危機：電力網障害が生活・産業・価格を直撃",
    period: "2021",
    direction: "volatile",
    category: "power_grid_failure",
    affectedTags: ["power", "grid", "energy", "utility", "weather", "manufacturing", "insurance", "datacenter"],
    shortSummary: "寒波でテキサス電力網が混乱し、停電、電力価格急騰、製造停止、生活被害が発生した。AI時代は電力網の脆弱性がさらに重要になる。",
    chain: ["異常気象", "発電/送電障害", "停電", "電力価格急騰", "製造/生活/保険被害"],
    coreMechanism: "電力網は全産業の基盤で、停止すると製造・医療・通信・データセンターへ一気に波及する。",
    earlySignals: ["需給逼迫", "予備率低下", "異常気象", "電力価格", "送電網老朽化"],
    wrongTakeaways: ["電力障害は公益株だけの話", "短期停電なら企業業績に影響しない"],
    usefulTakeaways: ["電力予備率と送電網投資を見る", "データセンター/半導体/製造の電力依存を見る"],
    modernAnalogyQuestions: ["AIデータセンター増加で電力網が耐えられるか？", "停電に強い企業/弱い企業は？"],
    primaryChecks: ["電力予備率", "電力価格", "送電網投資", "停電時間", "製造停止"],
    sourceHints: ["Texas power crisis 2021 market impact", "grid failure energy prices"],
  },
  {
    id: "south-africa-load-shedding",
    title: "南アフリカ計画停電：慢性的電力不足が成長率を削る",
    period: "2010s-2020s",
    direction: "down",
    category: "chronic_power_shortage",
    affectedTags: ["power", "grid", "mining", "emerging_market", "infrastructure", "manufacturing", "currency"],
    shortSummary: "慢性的な計画停電は鉱業、製造、通貨、投資心理を悪化させる。電力不足は一時イベントではなく国の成長制約になる。",
    chain: ["発電能力不足", "計画停電", "鉱業/製造停止", "成長率低下", "通貨/投資心理悪化"],
    coreMechanism: "安定電力がない国では、企業の潜在利益より供給制約が強く効く。",
    earlySignals: ["停電時間", "発電設備故障", "鉱山稼働", "通貨安", "設備投資減"],
    wrongTakeaways: ["資源が豊富なら成長できる", "停電は一時的な生活問題"],
    usefulTakeaways: ["電力インフラを国別リスクとして見る", "鉱業/製造の稼働率を確認する"],
    modernAnalogyQuestions: ["AI/鉱物/製造投資は電力制約で止まらないか？", "電力不足が通貨リスクになるか？"],
    primaryChecks: ["停電時間", "発電余力", "鉱山稼働", "通貨", "投資計画"],
    sourceHints: ["South Africa load shedding economic impact", "Eskom power crisis"],
  },
  {
    id: "california-insurance-retreat",
    title: "米住宅保険危機：気候災害で保険が買えなくなるリスク",
    period: "2020s",
    direction: "volatile",
    category: "climate_insurance_crisis",
    affectedTags: ["insurance", "climate", "wildfire", "housing", "real_estate", "reinsurance", "mortgage"],
    shortSummary: "山火事やハリケーンなど気候災害で保険会社が撤退・値上げし、住宅市場、住宅ローン、地方財政に波及する可能性がある。",
    chain: ["気候災害増加", "保険損失増", "保険料上昇/撤退", "住宅購入負担増", "不動産価格/住宅ローンに影響"],
    coreMechanism: "保険が成立しない地域では、不動産価値と住宅ローンの前提が揺らぐ。",
    earlySignals: ["保険会社撤退", "保険料上昇", "再保険料", "住宅販売", "災害損失"],
    wrongTakeaways: ["保険料上昇は保険会社に必ずプラス", "気候災害は災害後だけ見ればよい"],
    usefulTakeaways: ["保険会社の損害率と撤退を見る", "住宅市場・住宅ローンへの波及を見る"],
    modernAnalogyQuestions: ["保険不能地域が広がっていないか？", "住宅ローン/不動産価格に波及するか？"],
    primaryChecks: ["損害率", "再保険料", "保険撤退", "住宅価格", "住宅ローン延滞"],
    sourceHints: ["California home insurance crisis", "climate risk insurance retreat"],
  },
  {
    id: "eurozone-debt-crisis-2010",
    title: "欧州債務危機：国債金利が銀行・通貨・株式を揺らす",
    period: "2010-2012",
    direction: "down",
    category: "sovereign_debt_crisis",
    affectedTags: ["sovereign_debt", "bond_yield", "bank", "currency", "europe", "austerity", "risk_off"],
    shortSummary: "ギリシャなどの財政不安で国債金利が上昇し、銀行の保有国債、通貨、緊縮財政、景気後退へ連鎖した。",
    chain: ["財政不安", "国債金利上昇", "銀行含み損/資本不安", "緊縮財政", "景気悪化/通貨不安"],
    coreMechanism: "国債は安全資産という前提が崩れると、銀行・通貨・財政政策へ一気に波及する。",
    earlySignals: ["国債利回り上昇", "CDS拡大", "銀行保有国債", "格下げ", "緊縮策"],
    wrongTakeaways: ["先進国国債は常に安全", "財政問題は株に関係ない"],
    usefulTakeaways: ["国債金利と銀行の保有資産を見る", "財政政策と景気の悪循環を見る"],
    modernAnalogyQuestions: ["国債金利上昇は銀行/通貨/株式PERに効いていないか？", "財政余力はあるか？"],
    primaryChecks: ["国債利回り", "CDS", "格付け", "銀行保有国債", "財政赤字"],
    sourceHints: ["Eurozone debt crisis sovereign bond yields", "Greece debt crisis banks"],
  },
  {
    id: "uk-gilt-crisis-2022",
    title: "英国ギルト危機：財政不信と年金LDIの強制売り",
    period: "2022",
    direction: "volatile",
    category: "bond_market_liability_crisis",
    affectedTags: ["bond_yield", "fiscal", "pension", "currency", "leverage", "uk", "risk_off"],
    shortSummary: "大型減税案で英国債利回りが急騰し、年金基金のLDI戦略が強制売りに追い込まれ、中央銀行介入につながった。",
    chain: ["財政政策不信", "国債利回り急騰", "年金LDIの担保不足", "強制売り", "中央銀行介入"],
    coreMechanism: "国債市場でもレバレッジ戦略が集中すると、金利急変で強制売りが連鎖する。",
    earlySignals: ["国債利回り急騰", "通貨安", "担保要求", "年金基金リスク", "中央銀行介入"],
    wrongTakeaways: ["国債市場は安全で流動性が無限", "財政政策は株式だけに効く"],
    usefulTakeaways: ["金利上昇とレバレッジの組み合わせを見る", "政策信頼と通貨をセットで見る"],
    modernAnalogyQuestions: ["国債金利上昇で誰が強制売りに追い込まれるか？", "財政政策への信頼はあるか？"],
    primaryChecks: ["国債利回り", "通貨", "担保要求", "年金/保険のデュレーション", "中央銀行対応"],
    sourceHints: ["UK gilt crisis 2022 LDI pension", "bond yield fiscal crisis"],
  },
  {
    id: "global-food-price-crisis-2007",
    title: "世界食料価格危機：食品インフレが社会不安と政策介入を生む",
    period: "2007-2008",
    direction: "volatile",
    category: "food_price_social_unrest",
    affectedTags: ["food", "agriculture", "inflation", "fertilizer", "social_unrest", "emerging_market", "policy"],
    shortSummary: "穀物価格上昇は新興国の家計負担を直撃し、輸出規制、補助金、社会不安へ波及した。食料は政治リスクに直結する。",
    chain: ["穀物価格上昇", "食品インフレ", "家計負担増", "抗議/社会不安", "輸出規制/補助金"],
    coreMechanism: "食料価格は生活必需品のため、所得が低い地域ほど政治・社会不安に直結しやすい。",
    earlySignals: ["穀物価格", "肥料価格", "輸出規制", "食品CPI", "抗議活動"],
    wrongTakeaways: ["食品価格は消費関連だけ見ればよい", "新興国の食料問題は先進国株に関係ない"],
    usefulTakeaways: ["食品インフレと政治不安を接続する", "輸出規制と肥料価格を見る"],
    modernAnalogyQuestions: ["戦争/干ばつ/肥料不足が食料価格に効くか？", "食品インフレが政治不安になるか？"],
    primaryChecks: ["穀物価格", "肥料価格", "食品CPI", "輸出規制", "社会不安"],
    sourceHints: ["2007 2008 world food price crisis", "food riots export bans"],
  },
  {
    id: "ukraine-grain-fertilizer-2022",
    title: "ウクライナ戦争と食料・肥料：戦争が食卓と政治に届く",
    period: "2022-",
    direction: "volatile",
    category: "war_food_fertilizer_security",
    affectedTags: ["war", "food", "grain", "fertilizer", "shipping", "inflation", "emerging_market", "social_unrest"],
    shortSummary: "ウクライナ戦争は穀物、肥料、黒海輸送、食品インフレを通じて世界の食料安全保障に波及した。",
    chain: ["戦争/港湾リスク", "穀物輸出停滞", "肥料価格上昇", "食品インフレ", "新興国の社会不安"],
    coreMechanism: "戦争は資源だけでなく食料・肥料・輸送を通じて、生活コストと政治安定に届く。",
    earlySignals: ["穀物価格", "肥料価格", "黒海輸送", "輸出協定", "食品CPI"],
    wrongTakeaways: ["戦争は防衛と原油だけ見ればよい", "穀物価格は農業株だけの話"],
    usefulTakeaways: ["食料安全保障を地政学として見る", "肥料と物流も確認する"],
    modernAnalogyQuestions: ["戦争が食品価格や社会不安に波及していないか？", "輸出規制や港湾リスクは？"],
    primaryChecks: ["穀物価格", "肥料価格", "黒海輸送", "輸出規制", "食品CPI"],
    sourceHints: ["Ukraine war grain fertilizer food prices", "Black Sea grain deal"],
  },
  {
    id: "submarine-cable-red-sea-risk",
    title: "海底ケーブルリスク：通信網障害が金融・AI・軍事へ波及",
    period: "2020s",
    direction: "volatile",
    category: "subsea_cable_connectivity_risk",
    affectedTags: ["submarine_cable", "telecom", "internet", "ai", "finance", "military", "satellite", "cybersecurity"],
    shortSummary: "海底ケーブルはインターネット、金融取引、クラウド、AI、軍事通信の基盤。損傷や攻撃は通信遅延・迂回・衛星通信需要に波及する。",
    chain: ["海底ケーブル損傷/攻撃", "通信遅延/停止", "クラウド/金融/軍事影響", "迂回ルート", "衛星通信/冗長化需要"],
    coreMechanism: "デジタル経済の物理インフラである海底ケーブルが止まると、金融・AI・通信・安全保障に同時影響する。",
    earlySignals: ["ケーブル障害", "地政学緊張", "通信遅延", "迂回トラフィック", "衛星通信需要"],
    wrongTakeaways: ["クラウドは物理インフラに依存しない", "通信障害は通信会社だけの問題"],
    usefulTakeaways: ["通信の冗長性を見る", "衛星通信/地上局/海底ケーブル保守をセットで見る"],
    modernAnalogyQuestions: ["AI/金融/軍事通信はどの物理経路に依存しているか？", "衛星通信が代替になるか？"],
    primaryChecks: ["障害箇所", "通信遅延", "迂回容量", "衛星通信契約", "地政学緊張"],
    sourceHints: ["submarine cable risk Red Sea", "undersea cable internet finance military"],
  },
  {
    id: "rare-earth-china-japan-2010",
    title: "中国レアアース輸出制限：重要鉱物が外交カードになる",
    period: "2010",
    direction: "volatile",
    category: "critical_minerals_export_control",
    affectedTags: ["rare_earth", "china", "japan", "export_control", "ev", "defense", "semiconductor", "battery"],
    shortSummary: "中国のレアアース輸出制限は、重要鉱物がEV、半導体、防衛、電池、外交の戦略資源になることを示した。",
    chain: ["外交摩擦", "輸出制限", "レアアース価格上昇", "代替調達/リサイクル", "重要鉱物政策"],
    coreMechanism: "重要鉱物は少数国に供給が集中すると、価格だけでなく安全保障と産業政策の問題になる。",
    earlySignals: ["輸出規制", "価格上昇", "在庫積み増し", "代替鉱山投資", "政府補助金"],
    wrongTakeaways: ["資源制約は短期価格だけの話", "中国依存はすぐ代替できる"],
    usefulTakeaways: ["供給国集中と代替可能性を見る", "政府備蓄/補助金/リサイクルを見る"],
    modernAnalogyQuestions: ["EV/防衛/半導体の重要鉱物依存は？", "輸出規制が来たら誰が困り誰が得るか？"],
    primaryChecks: ["輸出規制", "価格", "供給国シェア", "政府備蓄", "代替素材"],
    sourceHints: ["China rare earth export restrictions 2010 Japan", "critical minerals supply chain"],
  },
  {
    id: "lithium-boom-bust-2021",
    title: "リチウム相場の急騰と急落：需要テーマでも供給過剰で崩れる",
    period: "2021-2024",
    direction: "volatile",
    category: "battery_materials_cycle",
    affectedTags: ["lithium", "battery", "ev", "critical_minerals", "commodity", "supply_chain", "china"],
    shortSummary: "EV需要でリチウム価格が急騰したが、供給増・需要鈍化・在庫調整で急落した。重要鉱物も一方向ではない。",
    chain: ["EV需要期待", "リチウム価格急騰", "鉱山投資/供給増", "需要鈍化/在庫", "価格急落"],
    coreMechanism: "大テーマの材料でも、供給投資が追いつくと価格サイクルは逆回転する。",
    earlySignals: ["価格急騰", "新規鉱山投資", "在庫増", "EV販売鈍化", "契約価格低下"],
    wrongTakeaways: ["EVが伸びるならリチウムは永遠に上がる", "重要鉱物は供給過剰にならない"],
    usefulTakeaways: ["需要だけでなく供給投資を見る", "在庫と価格契約を見る"],
    modernAnalogyQuestions: ["AI/電池/防衛素材でも供給過剰に変わらないか？", "価格高が新規供給を呼んでいないか？"],
    primaryChecks: ["価格", "在庫", "鉱山投資", "EV販売", "契約価格"],
    sourceHints: ["lithium price boom bust EV", "battery materials cycle"],
  },
  {
    id: "post-covid-labor-shortage-service",
    title: "コロナ後の人手不足：外食・物流・介護・建設の供給制約",
    period: "2021-2020s",
    direction: "volatile",
    category: "post_pandemic_labor_shortage",
    affectedTags: ["labor_shortage", "wages", "restaurant", "logistics", "healthcare", "construction", "automation", "inflation"],
    shortSummary: "コロナ後の労働市場変化で、外食、物流、介護、建設は需要が戻っても人手不足・賃金上昇・営業時間制限に悩んだ。",
    chain: ["労働参加率変化", "人手不足", "賃金上昇", "サービス供給制約", "値上げ/自動化投資"],
    coreMechanism: "需要が戻っても人が足りなければ売上機会を逃し、人件費が利益率を圧迫する。",
    earlySignals: ["求人倍率", "賃金上昇", "営業時間短縮", "配送遅延", "離職率"],
    wrongTakeaways: ["需要回復ならサービス企業は全部プラス", "人件費は価格転嫁できる"],
    usefulTakeaways: ["人手不足を売上制約として見る", "省人化・ロボット・予約SaaSの需要を見る"],
    modernAnalogyQuestions: ["需要はあるのに人手不足で売上化できない企業か？", "自動化投資の受益者は誰か？"],
    primaryChecks: ["求人倍率", "賃金", "人件費率", "営業時間", "自動化投資"],
    sourceHints: ["post COVID labor shortage restaurants logistics healthcare", "wage inflation services"],
  },
  {
    id: "construction-labor-shortage-reconstruction",
    title: "建設人手不足と復興需要：需要があっても工事が進まない",
    period: "2010s-2020s",
    direction: "volatile",
    category: "construction_capacity_constraint",
    affectedTags: ["construction", "labor_shortage", "reconstruction", "infrastructure", "wages", "materials", "japan"],
    shortSummary: "震災復興、老朽インフラ、再開発、防衛・半導体工場建設など需要は強くても、人手不足と資材高で利益率や工期が制約される。",
    chain: ["復興/インフラ需要", "建設人材不足", "賃金/資材高", "工期遅延", "利益率圧迫/選別受注"],
    coreMechanism: "建設は需要量より施工能力がボトルネック。受注が増えても利益が増えるとは限らない。",
    earlySignals: ["建設技能者不足", "資材価格", "工期遅延", "受注残", "粗利率"],
    wrongTakeaways: ["復興需要は建設株に無条件プラス", "受注残が多ければ安心"],
    usefulTakeaways: ["施工能力と粗利率を見る", "資材高・人件費・工期を確認する"],
    modernAnalogyQuestions: ["半導体工場/防衛/復興需要は施工能力に制約されないか？", "受注は利益に変わるか？"],
    primaryChecks: ["受注残", "粗利率", "資材価格", "労務費", "工期"],
    sourceHints: ["Japan construction labor shortage reconstruction demand", "construction capacity constraint"],
  },
  {
    id: "hospital-ransomware-healthcare",
    title: "病院ランサムウェア：医療・個人情報・社会インフラとしてのサイバー",
    period: "2020s",
    direction: "volatile",
    category: "healthcare_cyber_risk",
    affectedTags: ["cybersecurity", "healthcare", "hospital", "ransomware", "privacy", "public_health", "insurance"],
    shortSummary: "病院へのランサムウェアは診療停止、個人情報流出、保険、医療IT投資に波及する。医療サイバーは社会インフラリスク。",
    chain: ["病院攻撃", "診療/予約停止", "患者安全/個人情報問題", "復旧費用/保険", "医療セキュリティ投資"],
    coreMechanism: "医療は停止許容度が低く、サイバー障害が人命・規制・保険・IT投資に直結する。",
    earlySignals: ["病院攻撃増加", "診療停止", "個人情報流出", "規制罰則", "サイバー保険料"],
    wrongTakeaways: ["病院サイバーはIT部門だけの話", "復旧すれば影響終了"],
    usefulTakeaways: ["医療IT/セキュリティ投資を見る", "停止時間と規制リスクを見る"],
    modernAnalogyQuestions: ["医療機関のサイバー投資は増えるか？", "保険や規制がコスト構造を変えるか？"],
    primaryChecks: ["攻撃件数", "停止時間", "個人情報流出", "規制", "保険料"],
    sourceHints: ["hospital ransomware healthcare cyber risk", "healthcare cybersecurity market"],
  },
  {
    id: "data-center-power-water-constraint",
    title: "AIデータセンター制約：電力・水・送電網がAI成長の上限になる",
    period: "2020s",
    direction: "volatile",
    category: "ai_datacenter_resource_constraint",
    affectedTags: ["ai", "datacenter", "power", "water", "grid", "cooling", "utility", "semiconductor"],
    shortSummary: "AIデータセンター需要は強いが、電力契約、送電網、冷却、水、用地、許認可がボトルネックになる。AIテーマはGPUだけでは終わらない。",
    chain: ["AI需要拡大", "データセンター建設", "電力/水/冷却制約", "送電網投資", "電力会社/冷却/設備が受益"],
    coreMechanism: "AIの成長は計算資源だけでなく、物理インフラの制約に従う。",
    earlySignals: ["電力契約", "送電網混雑", "水使用反対", "冷却設備需要", "許認可遅延"],
    wrongTakeaways: ["AIはソフトウェアだけの話", "GPU需要だけ見れば十分"],
    usefulTakeaways: ["電力・水・冷却・用地をAIのボトルネックとして見る", "設備投資と許認可を見る"],
    modernAnalogyQuestions: ["AI需要は電力/水で止まらないか？", "受益はGPU以外のどこに広がるか？"],
    primaryChecks: ["電力契約", "水使用", "送電網投資", "冷却設備", "許認可"],
    sourceHints: ["AI data center power water constraint", "data center grid cooling"],
  }
];
