import type { MarketLesson } from "./market-lessons.js";

export const EXTRA_MARKET_LESSONS: MarketLesson[] = [
  {
    id: "dotcom-bubble-2000",
    title: "ドットコムバブル崩壊：本物のテーマでも全銘柄は勝たない",
    period: "1999-2002",
    direction: "down",
    category: "valuation_bubble",
    affectedTags: ["internet", "software", "growth", "bubble", "ipo", "unprofitable", "valuation"],
    shortSummary: "インターネットの流れは本物だったが、利益化できない企業まで買われ、資金環境が変わると急落した。",
    chain: ["新技術の期待", "赤字企業にも資金流入", "売上より物語が重視", "資金環境悪化", "利益化できない企業から崩れる"],
    coreMechanism: "大テーマが本物でも、勝つ企業と名ばかり企業は分かれる。",
    earlySignals: ["赤字拡大", "営業CFマイナス", "売上なしIPO", "PSR/PER過熱"],
    wrongTakeaways: ["テーマが本物なら何でも買える", "赤字は気にしなくていい"],
    usefulTakeaways: ["テーマと企業価値を分ける", "利益化への道筋を見る", "資金調達環境を見る"],
    modernAnalogyQuestions: ["AI/宇宙/量子の物語は売上利益に変わっているか？", "資金調達が止まっても生き残れるか？"],
    primaryChecks: ["売上成長", "営業CF", "粗利率", "資金調達", "バリュエーション"],
    sourceHints: ["dot-com bubble", "NASDAQ crash 2000"],
  },
  {
    id: "japan-asset-bubble-1990",
    title: "日本バブル崩壊：土地神話と信用膨張の逆回転",
    period: "1989-1992",
    direction: "down",
    category: "asset_bubble_credit",
    affectedTags: ["japan", "real_estate", "bank", "credit", "macro", "leverage"],
    shortSummary: "地価上昇を前提に信用が膨らみ、金融引き締めと資産価格下落で長期不況に入った。",
    chain: ["地価上昇", "担保価値上昇", "融資拡大", "金融引き締め", "担保価値下落と不良債権"],
    coreMechanism: "担保価格が上がるほど借入が増え、下がると逆回転する。",
    earlySignals: ["地価急騰", "貸出急増", "金融引き締め", "不動産在庫増"],
    wrongTakeaways: ["土地は下がらない", "含み益があるから安全"],
    usefulTakeaways: ["担保と信用の循環を見る", "低金利前提の事業を疑う"],
    modernAnalogyQuestions: ["金利上昇で資金繰りが悪化しないか？", "資産価格前提の利益ではないか？"],
    primaryChecks: ["地価", "金利", "貸出残高", "不良債権", "自己資本"],
    sourceHints: ["Japanese asset price bubble", "lost decade"],
  },
  {
    id: "asian-financial-crisis-1997",
    title: "アジア通貨危機：外貨建て債務と通貨安の連鎖",
    period: "1997-1998",
    direction: "down",
    category: "currency_debt_crisis",
    affectedTags: ["emerging_market", "currency", "debt", "bank", "export", "macro"],
    shortSummary: "外貨建て債務と資本流出が通貨安を呼び、債務負担増と銀行不安へ広がった。",
    chain: ["外貨建て債務増加", "資本流出", "通貨安", "債務負担増", "銀行/企業危機"],
    coreMechanism: "通貨安は輸出にプラスだけでなく、外貨負債には大きなマイナスになる。",
    earlySignals: ["外貨準備減少", "短期外債増加", "経常赤字", "通貨防衛"],
    wrongTakeaways: ["成長国なら安全", "通貨安は輸出にプラスだけ"],
    usefulTakeaways: ["債務の通貨を見る", "外貨準備と短期債務を見る"],
    modernAnalogyQuestions: ["為替変動が利益と債務にどう効くか？", "外貨建て負債は多いか？"],
    primaryChecks: ["為替", "外貨準備", "短期外債", "経常収支", "政策金利"],
    sourceHints: ["Asian financial crisis", "currency crisis 1997"],
  },
  {
    id: "ltcm-1998",
    title: "LTCM危機：賢いモデルも流動性で壊れる",
    period: "1998",
    direction: "volatile",
    category: "model_leverage_liquidity",
    affectedTags: ["hedge_fund", "leverage", "model", "liquidity", "spread", "risk"],
    shortSummary: "高度な裁定モデルでも、過剰レバレッジと市場ストレスで流動性が消えると破綻寸前になった。",
    chain: ["小さな価格差を大レバレッジで取る", "異常相場で逆行", "損失拡大", "流動性消失", "金融システム不安"],
    coreMechanism: "モデルが正しくても、資金が尽きるまでに価格が戻るとは限らない。",
    earlySignals: ["レバレッジ拡大", "流動性低下", "スプレッド異常", "同じ取引の集中"],
    wrongTakeaways: ["裁定なら安全", "賢い人がやるから安全"],
    usefulTakeaways: ["レバレッジは正しさを殺す", "流動性リスクを別管理する"],
    modernAnalogyQuestions: ["AI/クオンツが同じポジションに集中していないか？", "逃げられる流動性はあるか？"],
    primaryChecks: ["レバレッジ", "流動性", "スプレッド", "証拠金", "ポジション集中"],
    sourceHints: ["Long-Term Capital Management", "LTCM crisis"],
  },
  {
    id: "nikola-2020",
    title: "Nikola：夢の技術と実証不足の危険",
    period: "2020",
    direction: "down",
    category: "hype_technology_scandal",
    affectedTags: ["ev", "hydrogen", "hype", "fraud", "technology", "spac"],
    shortSummary: "EV/水素の強い物語で評価されたが、技術実証の弱さや疑義で急落した。",
    chain: ["脱炭素テーマ", "SPAC上場", "派手な物語", "技術疑義", "信頼低下"],
    coreMechanism: "未来技術は、実物・顧客・量産・売上の証拠がないと期待が剥がれやすい。",
    earlySignals: ["プロトタイプ中心", "売上不足", "調査報道", "提携条件が曖昧"],
    wrongTakeaways: ["未来技術なら赤字でも何でもよい", "提携があれば安心"],
    usefulTakeaways: ["技術実証を見る", "顧客が支払っているか見る", "量産可能性を見る"],
    modernAnalogyQuestions: ["宇宙/AI/量子の技術は実証済みか？", "提携は売上に変わるか？"],
    primaryChecks: ["製品実証", "売上", "顧客契約", "量産計画", "第三者検証"],
    sourceHints: ["Nikola Hindenburg report", "EV startup scandal"],
  },
  {
    id: "archegos-2021",
    title: "Archegos：見えない集中ポジションの強制解消",
    period: "2021",
    direction: "down",
    category: "hidden_leverage_margin_call",
    affectedTags: ["leverage", "margin_call", "prime_broker", "bank", "derivatives", "liquidity"],
    shortSummary: "デリバティブで見えにくい集中ポジションが膨らみ、追証と強制売却で関連株が急落した。",
    chain: ["見えにくい大ポジション", "株価下落", "担保不足", "強制売却", "金融機関損失"],
    coreMechanism: "表に出ないレバレッジは、崩れる時に一気に流動性を奪う。",
    earlySignals: ["不自然な上昇", "ブロック取引", "出来高急増", "金融機関損失"],
    wrongTakeaways: ["大株主が見えないなら集中はない", "出来高が多いから安全"],
    usefulTakeaways: ["見えないレバレッジを疑う", "ブロック売りを追う"],
    modernAnalogyQuestions: ["急騰銘柄に強制解消リスクはないか？", "大口売りが続いていないか？"],
    primaryChecks: ["大量保有", "ブロック取引", "出来高", "金融機関開示", "株価急落"],
    sourceHints: ["Archegos Capital Management", "margin call"],
  },
  {
    id: "china-education-2021",
    title: "中国教育株規制：政策一発で利益モデルが消える",
    period: "2021",
    direction: "down",
    category: "policy_business_model_risk",
    affectedTags: ["education", "china", "regulation", "policy", "adr", "platform"],
    shortSummary: "教育費負担軽減政策で営利型教育ビジネスが制限され、上場教育株の価値前提が崩れた。",
    chain: ["教育需要で高成長", "社会問題化", "規制強化", "営利モデル制限", "株価急落"],
    coreMechanism: "政策目的と企業利益が衝突すると、需要が強くてもビジネスモデルが変わる。",
    earlySignals: ["政府批判", "規制草案", "料金規制", "広告規制"],
    wrongTakeaways: ["需要が強いから規制されない", "成長率が高ければ安全"],
    usefulTakeaways: ["政策目的と企業利益の一致を見る", "規制産業は政策文書を読む"],
    modernAnalogyQuestions: ["AI/医療/教育/金融で社会負担が問題化していないか？", "制度変更で売上モデルが変わらないか？"],
    primaryChecks: ["政策文書", "規制草案", "当局発言", "料金規制", "広告規制"],
    sourceHints: ["China tutoring crackdown 2021", "education stocks regulation"],
  },
  {
    id: "evergrande-2021",
    title: "恒大集団：不動産デベロッパーの資金繰り連鎖",
    period: "2021-2023",
    direction: "down",
    category: "property_debt_crisis",
    affectedTags: ["real_estate", "china", "debt", "credit", "bank", "construction", "materials"],
    shortSummary: "高レバレッジ不動産開発の資金繰り問題が、建設・金融・消費へ波及した。",
    chain: ["借入で拡大", "規制で資金調達が締まる", "販売鈍化", "支払い遅延", "周辺産業へ波及"],
    coreMechanism: "不動産は金融・雇用・素材・地方経済と接続している。",
    earlySignals: ["社債利回り上昇", "販売鈍化", "支払い遅延", "在庫増加"],
    wrongTakeaways: ["大手不動産は必ず救われる", "建設中物件は安全資産"],
    usefulTakeaways: ["前受金と完成義務を見る", "社債市場を見る", "周辺産業への連鎖を見る"],
    modernAnalogyQuestions: ["不動産/建設/素材に信用収縮が来ていないか？", "社債利回りは上がっていないか？"],
    primaryChecks: ["社債利回り", "販売件数", "在庫", "支払い遅延", "規制"],
    sourceHints: ["Evergrande debt crisis", "China property crisis"],
  },
  {
    id: "terra-luna-2022",
    title: "Terra/Luna崩壊：高利回り商品と信頼の取り付け",
    period: "2022",
    direction: "down",
    category: "crypto_stablecoin_run",
    affectedTags: ["crypto", "stablecoin", "yield", "ponzi", "risk_off", "liquidity"],
    shortSummary: "高利回りとアルゴリズム型ステーブルコインへの信頼が崩れ、連鎖的な売りが起きた。",
    chain: ["高利回りで資金流入", "安定価値への信頼", "ペッグ崩れ", "出金/売り加速", "関連資産へ波及"],
    coreMechanism: "利回りの源泉が不明確な商品は、信頼が崩れると取り付けが起きる。",
    earlySignals: ["高すぎる利回り", "準備資産不透明", "ペッグ乖離", "出金増"],
    wrongTakeaways: ["安定と名前があれば安全", "高利回りは技術革新だから問題ない"],
    usefulTakeaways: ["利回りの源泉を見る", "準備資産を見る", "流動性を見る"],
    modernAnalogyQuestions: ["高利回りの源泉は何か？", "出金が増えたら持つか？"],
    primaryChecks: ["利回り源泉", "準備資産", "ペッグ", "出金", "流動性"],
    sourceHints: ["Terra Luna collapse", "algorithmic stablecoin"],
  },
  {
    id: "ftx-2022",
    title: "FTX破綻：顧客資産と関連会社リスク",
    period: "2022",
    direction: "down",
    category: "exchange_governance_failure",
    affectedTags: ["crypto", "exchange", "governance", "fraud", "liquidity", "contagion"],
    shortSummary: "顧客資産管理、関連会社取引、流動性不足、ガバナンス不全が一気に表面化した。",
    chain: ["取引所として信用獲得", "関連会社取引が不透明", "疑惑で出金急増", "流動性不足", "業界全体へ信用不安"],
    coreMechanism: "金融仲介業は、顧客資産の分別管理と信頼が商品そのもの。",
    earlySignals: ["関連会社取引", "監査不透明", "出金急増", "準備資産疑義"],
    wrongTakeaways: ["有名投資家が出資しているから安全", "取引量が多いから安全"],
    usefulTakeaways: ["顧客資産管理を見る", "関連当事者取引を見る", "金融業は信頼が商品"],
    modernAnalogyQuestions: ["顧客資産を預かるビジネスか？", "出金が殺到したら持つか？"],
    primaryChecks: ["監査", "顧客資産分別", "出金状況", "関連当事者取引", "準備資産"],
    sourceHints: ["FTX collapse", "customer assets", "Alameda Research"],
  },
  {
    id: "madoff-2008",
    title: "Madoff事件：安定しすぎる高成績を疑う",
    period: "2008",
    direction: "down",
    category: "ponzi_scheme",
    affectedTags: ["fraud", "asset_management", "ponzi", "governance", "audit", "trust"],
    shortSummary: "安定した高リターンを装ったが、実態はポンジスキームだった。",
    chain: ["安定成績で信用獲得", "紹介で資金流入", "運用実態が不透明", "出金増", "新規資金で支えられず破綻"],
    coreMechanism: "説明できない安定高収益は、運用成績ではなく構造リスクかもしれない。",
    earlySignals: ["成績が安定しすぎる", "運用不透明", "独立監査が弱い", "出金制限"],
    wrongTakeaways: ["長年続いたから本物", "損失が少ないから優秀"],
    usefulTakeaways: ["リターン源泉を見る", "独立監査と保管を見る", "安定しすぎる成績を疑う"],
    modernAnalogyQuestions: ["AI運用や高利回りの源泉は説明できるか？", "第三者が資産を確認しているか？"],
    primaryChecks: ["監査", "保管機関", "運用手法", "出金条件", "取引記録"],
    sourceHints: ["Bernie Madoff", "Ponzi scheme"],
  },
  {
    id: "toshiba-accounting-2015",
    title: "東芝不正会計：名門企業でもガバナンスは崩れる",
    period: "2015-2017",
    direction: "down",
    category: "japan_governance_accounting",
    affectedTags: ["japan", "accounting", "governance", "conglomerate", "audit", "scandal"],
    shortSummary: "名門大企業でも不適切会計と事業損失が重なると、信頼・資本・上場維持問題へ広がる。",
    chain: ["名門企業として信頼", "不適切会計", "監査不信", "事業損失", "資本政策/事業売却"],
    coreMechanism: "ブランドや歴史はガバナンス不全を防がない。",
    earlySignals: ["利益目標圧力", "監査遅延", "内部統制不備", "経営陣交代"],
    wrongTakeaways: ["名門企業なら安心", "会計問題は一時的"],
    usefulTakeaways: ["企業規模とガバナンスは別", "監査遅延は重大", "セグメントごとに見る"],
    modernAnalogyQuestions: ["大企業ブランドに安心していないか？", "説明は一貫しているか？"],
    primaryChecks: ["監査報告", "内部統制", "セグメント損益", "減損", "資本政策"],
    sourceHints: ["Toshiba accounting scandal", "Japan corporate governance"],
  },
  {
    id: "takata-airbag-2014",
    title: "タカタ：品質問題が供給網全体を巻き込む",
    period: "2014-2017",
    direction: "down",
    category: "product_liability_supply_chain",
    affectedTags: ["automotive", "supplier", "safety", "recall", "liability", "bankruptcy"],
    shortSummary: "エアバッグ欠陥が世界的リコールと訴訟へ広がり、サプライヤーの存続を揺るがした。",
    chain: ["部品が世界中に出荷", "安全問題発覚", "大規模リコール", "補償/訴訟", "資金繰り悪化"],
    coreMechanism: "安全部品は出荷済み数量の分だけ潜在責任が膨らむ。",
    earlySignals: ["事故報告", "リコール拡大", "当局調査", "補償引当"],
    wrongTakeaways: ["部品会社だから影響は限定的", "リコールは一回で終わる"],
    usefulTakeaways: ["出荷済み責任を見る", "安全部品は訴訟リスクを重く見る"],
    modernAnalogyQuestions: ["EV/電池/医療機器で出荷済み責任はないか？", "品質問題が顧客全体に広がるか？"],
    primaryChecks: ["リコール", "事故報告", "当局調査", "引当金", "訴訟"],
    sourceHints: ["Takata airbag recall", "product liability"],
  },
  {
    id: "tesla-2019-2021",
    title: "Tesla急騰：最大懸念を実行で突破した再評価",
    period: "2019-2021",
    direction: "up",
    category: "execution_revaluation",
    affectedTags: ["ev", "battery", "growth", "manufacturing", "short_interest", "software", "brand"],
    shortSummary: "資金繰り・量産懸念が強かったが、生産台数、粗利、キャッシュフロー改善で再評価された。",
    chain: ["倒産/量産懸念", "生産改善", "粗利改善", "倒産リスク低下", "成長企業として再評価"],
    coreMechanism: "市場が疑う最大リスクを数字で突破すると、評価軸が一気に変わる。",
    earlySignals: ["生産台数改善", "粗利率改善", "営業CF改善", "空売り比率"],
    wrongTakeaways: ["赤字企業は全部ダメ", "空売りが多ければ必ず上がる"],
    usefulTakeaways: ["最大懸念の解消を見る", "量産と粗利をセットで見る"],
    modernAnalogyQuestions: ["宇宙/AI/EV企業の最大懸念は何か？", "数字で解消され始めたか？"],
    primaryChecks: ["生産台数", "粗利率", "営業CF", "受注", "空売り"],
    sourceHints: ["Tesla profitability 2020", "Tesla short squeeze"],
  },
  {
    id: "nvidia-ai-2023",
    title: "NVIDIA AI相場：ボトルネックを握る企業に利益が集中",
    period: "2023-2026",
    direction: "up",
    category: "bottleneck_winner",
    affectedTags: ["ai", "gpu", "semiconductor", "datacenter", "cloud", "power", "supply_chain"],
    shortSummary: "AI需要でGPUがボトルネックになり、計算資源を握る企業に売上・利益が集中した。",
    chain: ["生成AI需要", "GPU不足", "価格決定力", "売上利益急拡大", "電力/冷却/データセンターへ波及"],
    coreMechanism: "大テーマでは、最も不足しているボトルネックを握る企業が強い。",
    earlySignals: ["受注急増", "供給制約", "粗利率上昇", "主要顧客CAPEX"],
    wrongTakeaways: ["AI銘柄なら全部同じ", "GPU以外は関係ない"],
    usefulTakeaways: ["ボトルネックを探す", "価格決定力を見る", "周辺インフラへ波及を見る"],
    modernAnalogyQuestions: ["その企業はAIのどの不足資源を握るか？", "電力/冷却も見るべきか？"],
    primaryChecks: ["データセンター売上", "粗利率", "供給能力", "顧客CAPEX", "在庫"],
    sourceHints: ["Nvidia AI boom", "GPU supply bottleneck"],
  },
  {
    id: "wework-2019",
    title: "WeWork：成長物語とユニットエコノミクスの衝突",
    period: "2019",
    direction: "down",
    category: "private_market_excess",
    affectedTags: ["startup", "venture", "unprofitable", "real_estate", "valuation", "governance"],
    shortSummary: "未上場評価は高かったが、上場時に収益性・統治・実態が問われ評価が急落した。",
    chain: ["巨額資金流入", "成長優先", "赤字拡大", "上場審査で疑問", "評価額急落"],
    coreMechanism: "未上場市場の評価は、上場市場の規律に耐えられないことがある。",
    earlySignals: ["赤字拡大", "関連当事者取引", "上場延期", "評価額引き下げ"],
    wrongTakeaways: ["有名ファンドが入っていれば安心", "売上成長だけで十分"],
    usefulTakeaways: ["ユニットエコノミクスを見る", "ガバナンスを見る", "評価額よりキャッシュを見る"],
    modernAnalogyQuestions: ["IPO候補は単位経済性が成立しているか？", "有名投資家の名前に引っ張られていないか？"],
    primaryChecks: ["営業損失", "ユニットエコノミクス", "ガバナンス", "目論見書", "評価額推移"],
    sourceHints: ["WeWork IPO failure", "SoftBank Vision Fund"],
  },
  {
    id: "spac-boom-2020",
    title: "SPAC/テーマIPO相場：上場しやすさと品質は別",
    period: "2020-2021",
    direction: "volatile",
    category: "speculative_listing_cycle",
    affectedTags: ["spac", "ipo", "ev", "space", "hype", "unprofitable", "growth"],
    shortSummary: "SPACでEV/宇宙などの上場が増えたが、売上未成熟・過大予想・ロックアップ後需給で多くが失速した。",
    chain: ["金融緩和", "SPAC上場増", "テーマ人気", "実績未達", "ロックアップ/希薄化で失速"],
    coreMechanism: "上場できたことは事業品質の証明ではない。",
    earlySignals: ["売上未達", "予想下方修正", "ロックアップ解除", "希薄化"],
    wrongTakeaways: ["上場したから信用できる", "宇宙/EVなら全部大化け"],
    usefulTakeaways: ["上場方式と事業品質を分ける", "ロックアップと希薄化を見る"],
    modernAnalogyQuestions: ["新規上場銘柄に実績はあるか？", "テーマだけで買われていないか？"],
    primaryChecks: ["目論見書", "売上実績", "ロックアップ", "希薄化", "決算予想"],
    sourceHints: ["SPAC boom 2020", "de-SPAC performance"],
  },
  {
    id: "hertz-bankruptcy-2020",
    title: "Hertz破綻株急騰：株価上昇と株主価値は別",
    period: "2020",
    direction: "volatile",
    category: "bankruptcy_speculation",
    affectedTags: ["bankruptcy", "retail", "meme", "distress", "travel", "credit"],
    shortSummary: "破綻手続き中にも個人投資家の買いで株価が急騰したが、株主価値は債権者順位に左右される。",
    chain: ["破綻で急落", "安値感で買い", "短期急騰", "資本構成問題", "株主価値の有無が問われる"],
    coreMechanism: "破綻企業の株式は残余請求権。株価が動いても価値が残るとは限らない。",
    earlySignals: ["破綻申請", "債務超過", "債券価格", "裁判所資料"],
    wrongTakeaways: ["安い株価ならお得", "有名企業なら株主も助かる"],
    usefulTakeaways: ["資本構成を見る", "株主の順位を理解する"],
    modernAnalogyQuestions: ["株主価値が残る資本構成か？", "債券はどう評価されているか？"],
    primaryChecks: ["破綻資料", "債券価格", "債務総額", "再建計画", "希薄化"],
    sourceHints: ["Hertz bankruptcy stock rally", "retail speculation"],
  },
  {
    id: "abenomics-2012",
    title: "アベノミクス相場：政策・為替・期待の同時変化",
    period: "2012-2015",
    direction: "up",
    category: "policy_reflation_currency",
    affectedTags: ["japan", "policy", "currency", "export", "central_bank", "inflation", "equity"],
    shortSummary: "金融緩和、財政政策、成長戦略期待、円安が重なり、日本株と輸出企業が再評価された。",
    chain: ["政策転換期待", "金融緩和", "円安/株高", "輸出企業利益期待", "海外資金流入"],
    coreMechanism: "政策・為替・企業利益の方向が揃うと、指数全体が再評価されやすい。",
    earlySignals: ["金融緩和姿勢", "為替変化", "海外投資家買い", "企業業績上方修正"],
    wrongTakeaways: ["政策だけで永遠に上がる", "円安は全企業にプラス"],
    usefulTakeaways: ["政策と業績の接続を見る", "為替感応度を分ける"],
    modernAnalogyQuestions: ["政策と企業利益が同じ方向か？", "為替は追い風か逆風か？"],
    primaryChecks: ["日銀政策", "為替", "企業想定為替", "海外投資家動向", "業績修正"],
    sourceHints: ["Abenomics stock market", "BOJ monetary easing"],
  },
  {
    id: "russia-ukraine-energy-2022",
    title: "ロシア・ウクライナ侵攻：地政学とエネルギー価格の連鎖",
    period: "2022",
    direction: "volatile",
    category: "geopolitical_energy_shock",
    affectedTags: ["energy", "oil", "gas", "defense", "food", "shipping", "inflation", "geopolitics"],
    shortSummary: "侵攻と制裁でエネルギー・穀物・物流が揺れ、インフレ、防衛、資源、欧州景気へ波及した。",
    chain: ["軍事侵攻", "制裁/供給不安", "エネルギー価格上昇", "インフレ", "金融引き締め/景気不安"],
    coreMechanism: "地政学ショックは資源価格と政策対応を通じて、企業コストと市場心理へ波及する。",
    earlySignals: ["軍事緊張", "制裁", "資源価格", "物流混乱", "防衛予算"],
    wrongTakeaways: ["遠い国の戦争は関係ない", "資源高は資源企業だけの話"],
    usefulTakeaways: ["資源・物流・インフレの連鎖を見る", "防衛/エネルギー政策を見る"],
    modernAnalogyQuestions: ["地政学が原材料・物流・需要にどう効くか？", "防衛/エネルギー投資は増えるか？"],
    primaryChecks: ["資源価格", "制裁", "防衛予算", "物流", "インフレ", "企業コスト"],
    sourceHints: ["Russia Ukraine energy shock", "2022 commodity inflation"],
  },
  {
    id: "ozempic-2023",
    title: "GLP-1/肥満薬相場：医薬品が消費行動まで変える可能性",
    period: "2023-2026",
    direction: "up",
    category: "healthcare_behavior_shift",
    affectedTags: ["healthcare", "pharma", "biotech", "consumer", "food", "insurance", "obesity"],
    shortSummary: "肥満症薬の普及期待で製薬企業が再評価される一方、食品・医療費・保険・消費行動への波及も議論された。",
    chain: ["治療効果への期待", "処方拡大", "製薬売上拡大", "消費行動変化の議論", "周辺業界の再評価"],
    coreMechanism: "医薬品の大型テーマは、治療市場だけでなく消費・保険・医療費へ波及する。",
    earlySignals: ["処方数", "供給制約", "臨床データ", "保険適用", "副作用"],
    wrongTakeaways: ["薬が出たら関連消費は全部下がる", "製薬だけ見れば十分"],
    usefulTakeaways: ["実際の処方と供給を見る", "二次影響は慎重に見る"],
    modernAnalogyQuestions: ["医療テーマは消費行動に波及するか？", "供給制約と保険適用はどうか？"],
    primaryChecks: ["臨床結果", "処方数", "保険適用", "供給能力", "副作用", "競合薬"],
    sourceHints: ["GLP-1 obesity drugs", "Ozempic market impact"],
  },
  {
    id: "china-ev-price-war-2023",
    title: "中国EV価格競争：成長市場でも利益率が壊れる",
    period: "2023-2026",
    direction: "down",
    category: "price_war_margin_pressure",
    affectedTags: ["ev", "automotive", "china", "battery", "consumer", "margin"],
    shortSummary: "EV市場は成長しても、価格競争が激化すると販売台数より利益率が問題になる。",
    chain: ["市場成長", "参入企業増加", "価格競争", "利益率低下", "弱い企業が淘汰"],
    coreMechanism: "需要が伸びても、供給過多と価格競争で株主価値が増えないことがある。",
    earlySignals: ["値下げ", "在庫増", "粗利率低下", "補助金変更", "販売奨励金"],
    wrongTakeaways: ["市場成長なら全社儲かる", "販売台数だけ見ればよい"],
    usefulTakeaways: ["粗利率と価格競争を見る", "供給過多を確認する"],
    modernAnalogyQuestions: ["AI/EV/宇宙でも供給過多になっていないか？", "成長が利益に変わっているか？"],
    primaryChecks: ["ASP", "粗利率", "在庫", "販売台数", "補助金", "値下げ"],
    sourceHints: ["China EV price war", "EV margins"],
  },
  {
    id: "yen-carry-unwind-2024",
    title: "円キャリー巻き戻し：為替・金利・レバレッジの同時逆回転",
    period: "2024",
    direction: "volatile",
    category: "currency_carry_unwind",
    affectedTags: ["currency", "japan", "carry_trade", "interest_rate", "leverage", "risk_off"],
    shortSummary: "低金利通貨で資金を借りて高リターン資産へ向かう取引は、金利・為替・ボラ上昇で一気に巻き戻ることがある。",
    chain: ["低金利通貨で借入", "高利回り/株へ投資", "為替反転", "損失/証拠金悪化", "ポジション解消で市場が荒れる"],
    coreMechanism: "為替と金利の前提が崩れると、複数市場で同時にリスク削減が起きる。",
    earlySignals: ["急な円高", "金利差縮小", "ボラ上昇", "株式急落", "証拠金悪化"],
    wrongTakeaways: ["為替は輸出企業だけの話", "金利差がある限り安全"],
    usefulTakeaways: ["為替・金利・レバレッジをセットで見る", "混雑ポジションを疑う"],
    modernAnalogyQuestions: ["円高が一気に来たら誰が困るか？", "キャリー取引の巻き戻しが株に来ていないか？"],
    primaryChecks: ["為替", "日米金利差", "ボラティリティ", "先物ポジション", "証拠金"],
    sourceHints: ["yen carry trade unwind", "currency volatility"],
  },
  {
    id: "space-starlink-connectivity",
    title: "Starlink的衛星通信：宇宙テーマは通信・防災・安全保障へ接続",
    period: "2020-2026",
    direction: "up",
    category: "space_connectivity_infrastructure",
    affectedTags: ["space", "satellite", "starlink", "telecom", "defense", "disaster", "iot"],
    shortSummary: "衛星通信は宇宙ロマンだけでなく、災害時通信、遠隔地通信、防衛、船舶航空、IoTへ広がるインフラテーマ。",
    chain: ["低軌道衛星普及", "通信空白地帯を補完", "防災/安全保障需要", "端末/地上局/運用ソフトへ波及", "収益化の時間差"],
    coreMechanism: "宇宙テーマは売上化まで長いが、通信・防災・安全保障の実需と接続すると強い。",
    earlySignals: ["政府契約", "通信会社提携", "災害利用", "端末普及", "周波数/規制"],
    wrongTakeaways: ["宇宙なら全部すごい", "打ち上げ成功だけで十分"],
    usefulTakeaways: ["契約と売上化を見る", "地上インフラも見る", "防災/安全保障需要と接続する"],
    modernAnalogyQuestions: ["Starlink的変化が国内企業にどう効くか？", "売上化できる部品/通信/運用はどこか？"],
    primaryChecks: ["契約開示", "政府調達", "通信規制", "地上局", "端末普及", "売上貢献"],
    sourceHints: ["Starlink satellite internet", "space connectivity"],
  },
];
