import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { todayJst } from "./date.js";

function readText(path: string): string {
  return existsSync(path) ? readFileSync(path, "utf-8") : "";
}

function strip(text: string, max = 220): string {
  const cleaned = text
    .replace(/```[\s\S]*?```/g, "")
    .replace(/[#*_`>|]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  return cleaned.length > max ? `${cleaned.slice(0, max)}…` : cleaned;
}

function section(text: string, title: string, maxLines = 6): string[] {
  if (!text) return [];
  const lines = text.split("\n");
  const start = lines.findIndex(line => line.trim() === `## ${title}`);
  if (start < 0) return [];
  const picked: string[] = [];
  for (const line of lines.slice(start + 1)) {
    if (line.startsWith("## ")) break;
    const trimmed = line.trim();
    if (trimmed) picked.push(strip(trimmed, 120));
    if (picked.length >= maxLines) break;
  }
  return picked;
}

function main() {
  const date = todayJst();
  const strategic = readText("reports/strategic_advice_latest.md");
  const pipeline = readText("reports/pipeline_health_summary_latest.md");
  const committee = readText("reports/stock_pro_committee_latest.md");
  const roadmap = readText("reports/stock_pro_improvement_roadmap_latest.md");
  const refresh = readText("reports/pro_knowledge_refresh_latest.md");

  const data = {
    generatedAt: date,
    headline: "alpha-pon Pro Dashboard",
    summary: {
      strategic: strip(section(strategic, "今日まず見る穴", 4).join(" ") || strategic || "strategic advice未生成"),
      pipeline: strip(section(pipeline, "confidence", 4).join(" ") || pipeline || "pipeline health未生成"),
      committee: strip(committee || "Pro会議未生成", 260),
      roadmap: section(roadmap, "priority improvements", 8),
      refresh: section(refresh, "refresh queue", 6)
    },
    reports: [
      { key: "strategic", label: "司令塔", path: "reports/strategic_advice_latest.md", available: Boolean(strategic) },
      { key: "pipeline", label: "データ信頼度", path: "reports/pipeline_health_summary_latest.md", available: Boolean(pipeline) },
      { key: "committee", label: "Pro会議", path: "reports/stock_pro_committee_latest.md", available: Boolean(committee) },
      { key: "roadmap", label: "改善ロードマップ", path: "reports/stock_pro_improvement_roadmap_latest.md", available: Boolean(roadmap) },
      { key: "refresh", label: "Pro知識更新", path: "reports/pro_knowledge_refresh_latest.md", available: Boolean(refresh) }
    ],
    candidates: []
  };

  mkdirSync("design/app", { recursive: true });
  const js = [
    "/* generated by src/report-ui-data.ts */",
    `window.AP_GENERATED = ${JSON.stringify(data, null, 2)};`,
    "if (window.AP) window.AP.generated = window.AP_GENERATED;",
    ""
  ].join("\n");
  writeFileSync(join("design", "app", "data.generated.js"), js, "utf-8");
  console.log("generated design/app/data.generated.js");
}

main();
